upstream zammad-railsserver {
  server zammad-railsserver:3000;
}

upstream zammad-websocket {
  server zammad-websocket:6042;
}

server {
  listen 80;
  listen [::]:80;

  server_name localhost;
  server_tokens off;
  root /opt/zammad/public;

  access_log /dev/stdout;
  error_log /dev/stdout;

  client_max_body_size 50M;
  large_client_header_buffers 4 32k;

  location = /geimser/geimser.css {
    alias /opt/zammad/contrib/geimser/geimser.css;
    add_header Cache-Control "public, max-age=300";
  }

  location = /geimser/geimser.js {
    alias /opt/zammad/contrib/geimser/geimser.js;
    add_header Cache-Control "public, max-age=300";
  }

  location = /api/v1/system_assets/product_logo/geimser-logo-v2.png {
    alias /opt/zammad/public/assets/images/geimser-logo.png;
    add_header Cache-Control "public, max-age=300";
  }

  location ~ ^/(assets/|robots.txt|humans.txt|favicon.ico|apple-touch-icon.png) {
    expires max;
  }

  location /ws {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header CLIENT_IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 86400;
    proxy_pass http://zammad-websocket;
  }

  location /cable {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header CLIENT_IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 86400;
    proxy_pass http://zammad-railsserver;
  }

  location / {
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header CLIENT_IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-User "";
    proxy_read_timeout 300;

    proxy_set_header Accept-Encoding "";
    sub_filter_types text/html;
    sub_filter_once on;
    sub_filter '</head>' '<link rel="stylesheet" href="/geimser/geimser.css?v=11"><script src="/geimser/geimser.js?v=2"></script></head>';

    proxy_pass http://zammad-railsserver;

    gzip on;
    gzip_types text/plain text/xml text/css image/svg+xml application/javascript application/x-javascript application/json application/xml;
    gzip_proxied any;
  }
}
