---
x-geimser-zammad-build: &geimser-zammad-build
  image: ${GEIMSER_IMAGE_REPO:-itsm-geimser-zammad}:${VERSION:-7.0.1-0048}
  build:
    context: .
    dockerfile: docker/geimser-zammad/Dockerfile
    args:
      VERSION: ${VERSION:-7.0.1-0048}

services:
  zammad-backup:
    <<: *geimser-zammad-build
    platform: ${DOCKER_PLATFORM:-linux/arm64}
  zammad-elasticsearch:
    platform: ${DOCKER_PLATFORM:-linux/arm64}
  zammad-init:
    <<: *geimser-zammad-build
    platform: ${DOCKER_PLATFORM:-linux/arm64}
  zammad-memcached:
    platform: ${DOCKER_PLATFORM:-linux/arm64}
  zammad-nginx:
    <<: *geimser-zammad-build
    platform: ${DOCKER_PLATFORM:-linux/arm64}
  zammad-postgresql:
    platform: ${DOCKER_PLATFORM:-linux/arm64}
  zammad-railsserver:
    <<: *geimser-zammad-build
    platform: ${DOCKER_PLATFORM:-linux/arm64}
    healthcheck:
      start_period: 600s
      retries: 10
  zammad-redis:
    platform: ${DOCKER_PLATFORM:-linux/arm64}
  zammad-scheduler:
    <<: *geimser-zammad-build
    platform: ${DOCKER_PLATFORM:-linux/arm64}
  zammad-websocket:
    <<: *geimser-zammad-build
    platform: ${DOCKER_PLATFORM:-linux/arm64}
